# Generated by Django 5.2.8 on 2025-11-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_update_recommendation_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='text',
            field=models.TextField(help_text='Detailed recommendation or feedback'),
        ),
    ]
