# Generated by Django migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_collectionorder_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='talabat_url',
            field=models.URLField(blank=True, help_text='Talabat URL for this menu', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='menu_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of menu items for change detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='last_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time menu was synced from Talabat', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='talabat_id',
            field=models.IntegerField(blank=True, help_text='Original Talabat item ID', null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='item_hash',
            field=models.CharField(blank=True, db_index=True, help_text='SHA256 hash for change detection', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='section_name',
            field=models.CharField(blank=True, help_text='Section/category name from Talabat', max_length=200),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['item_hash'], name='orders_men_item_h_abc123_idx'),
        ),
    ]

