# Generated by Django 5.2.8 on 2025-12-25 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_talabat_sync_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='menuitem',
            new_name='orders_menu_item_ha_d6b2fe_idx',
            old_name='orders_men_item_h_abc123_idx',
        ),
    ]
