# Generated by Django 5.2.8 on 2025-12-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rename_orders_men_item_h_abc123_idx_orders_menu_item_ha_d6b2fe_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='talabat_id',
            field=models.BigIntegerField(blank=True, help_text='Original Talabat item ID', null=True),
        ),
    ]
