# Generated by Django 5.2.8 on 2025-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_change_talabat_id_to_bigint'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='note',
            field=models.TextField(blank=True, help_text='Special instructions or modifications for this item'),
        ),
    ]

